In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.datasets import load_iris
iris=load_iris()

In [ ]:
X=iris.data
y=iris.target
feature_names=iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
X[:5],y

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [ ]:
#Take 30% as test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

X_train[:10]

(112, 4)
(38, 4)
(112,)
(38,)


array([[5.1, 2.5, 3. , 1.1],
       [5.3, 3.7, 1.5, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [6.4, 3.2, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.8, 2.6, 4. , 1.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 2.5, 5. , 1.9]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
Cl_knn = KNeighborsClassifier(n_neighbors=3)
Cl_knn.fit(X_train, y_train)
y_pred = Cl_knn.predict(X_test)

In [ ]:
a=metrics.accuracy_score(y_test,y_pred)
print("Accuracy:",a)

Accuracy: 0.9736842105263158


In [ ]:
sample = [[5, 5, 1, 2], [2, 4, 5, 5], [1, 1, 1, 1]]
p=Cl_knn.predict(sample)
Prediction=[iris.target_names[i] for i in p]
print("Predictions:",Prediction)

Predictions: ['setosa', 'virginica', 'setosa']
